"""Initial migration

Revision ID: 272c8b8b89f9
Revises: 
Create Date: 2025-03-02 17:40:05.521368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '272c8b8b89f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_model')
    # ### end Alembic commands ###
